<a href="https://colab.research.google.com/github/sowmyarajesh/PythonMachingLearning/blob/main/pyTorch_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Transpose Vector, Transpose matrix using numpy and pytorch

In [1]:
import numpy as np
import torch

In [4]:
# create a vector
nv = np.array ([[1,2,3,4,5]])
print(nv)

#transpose it
print(nv.T)

[[1 2 3 4 5]]
[[1]
 [2]
 [3]
 [4]
 [5]]


In [5]:
nm = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(nm)
print(nm.T)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [6]:
# using pytorch

tv = torch.tensor([[1,2,3,4]])
print(tv.T)

tensor([[1],
        [2],
        [3],
        [4]])


In [7]:
tm = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(tm.T)

tensor([[ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11],
        [ 4,  8, 12]])


# Dot Product

Dot product is also called Scalar product.

Dot product can be done only with two vectors of same length or two square matrix of same shape.

Dot product can be represented as one of the following format in the code


*   a.b
*   <a,b>
*   a<sup>T</sup> b

dot product is calculated using the formula

a.b = SUM(a<sub>i</sub>b<sub>i</sub>)  

where i = 1,2...n




using numpy

In [8]:
v1 = np.array([1,2,3,4])
v2 = np.array([1,-1,0,-1])
# dot product function
print(np.dot(v1,v2))

# dot product using formula
print(np.sum(v1*v2))


-5
-5


In [10]:
v1 = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4],[1,2,3,4]])
v2 = np.array([[1,-1,0,-1],[1,-1,0,-1],[1,-1,0,-1],[1,-1,0,-1]])
# dot product function
print(np.dot(v1,v2))

# dot product using formula
print(np.sum(v1*v2))

[[ 10 -10   0 -10]
 [ 10 -10   0 -10]
 [ 10 -10   0 -10]
 [ 10 -10   0 -10]]
-20


using pytorch

In [11]:
v1 = torch.tensor([1,2,3,4])
v2 = torch.tensor([1,-1,0,-1])
# dot product function
print(torch.dot(v1,v2))

# dot product using formula
print(torch.sum(v1*v2))

tensor(-5)
tensor(-5)
